### ISSUE TITLE
Project is a little bit too complex

### ISSUE THREAD

**Issue by 18616505009** [andriydruk/BonjourBrowser#5]
Thank you for this demo and I just made my application work properly on my device.I want to give some suggestions no offence,when you are showing some functional project can we just make a simple UI?I know it's suggested to uses fragments instead of activties but is hard to analysize your core code.Again,my thanks!

**Comment by andriydruk** [comment]
Hi. Yes, totally agree. This app became too complex for demonstrating usage of RxDNSSD. But I won't change it because some amount of people use it from Google Play.
I created [another issue](https://github.com/andriydruk/RxDNSSD/issues/14) in RxDNSSD repo and I'm going to implement it there. If you can help with it, PR is welcome.
